language: python
python:
  - 3.4  
install:
  - pip install numpy matplotlib numexpr xlrd pandas
  - python setup.py install
script:
    python3 -m pandastable.tests

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
